import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";

const initialState = {
  addresses: {
    sub_districts: [],
    districts: [
      "Quận Ba Đình",
      "Quận Bắc Từ Liêm",
      "Quận Cầu Giấy",
      "Quận Đống Đa",
      "Quận Hà Đông",
      "Quận Hai Bà Trưng",
      "Quận Hoàn Kiếm",
      "Quận Hoàng Mai",
      "Quận Long Biên",
      "Quận Nam Từ Liêm",
      "Quận Tây Hồ",
      "Quận Thanh Xuân",
      "Thị xã Sơn Tây",
      "Huyện Ba Vì",
      "Huyện Chương Mỹ",
      "Huyện Đan Phượng",
      "Huyện Đông Anh",
      "Huyện Gia Lâm",
      "Huyện Hoài Đức",
      "Huyện Mê Linh",
      "Huyện Mỹ Đức",
      "Huyện Phú Xuyên",
      "Huyện Phúc Thọ",
      "Huyện Quốc Oai",
      "Huyện Sóc Sơn",
      "Huyện Thạch Thất",
      "Huyện Thanh Oai",
      "Huyện Thanh Trì",
      "Huyện Thường Tín",
      "Huyện Ứng Hòa",
      "Thành phố Thủ Đức",
      "Quận 1",
      "Quận 3",
      "Quận 4",
      "Quận 5",
      "Quận 6",
      "Quận 7",
      "Quận 8",
      "Quận 10",
      "Quận 11",
      "Quận 12",
      "Quận Bình Tân",
      "Quận Bình Thạnh",
      "Quận Gò Vấp",
      "Quận Phú Nhuận",
      "Quận Tân Bình",
      "Quận Tân Phú",
      "Huyện Bình Chánh",
      "Huyện Cần Giờ",
      "Huyện Củ Chi",
      "Huyện Hóc Môn",
      "Huyện Nhà Bè",
      "Quận Cẩm Lệ",
      "Quận Hải Châu",
      "Quận Liên Chiểu",
      "Quận Ngũ Hành Sơn",
      "Quận Sơn Trà",
      "Quận Thanh Khê",
      "Huyện Hòa Vang",
      "Huyện Hoàng Sa",
      "Quận Bình Thủy",
      "Quận Cái Răng",
      "Quận Ninh Kiều",
      "Quận Ô Môn",
      "Quận Thốt Nốt",
      "Huyện Cờ Đỏ",
      "Huyện Phong Điền",
      "Huyện Thới Lai",
      "Huyện Vĩnh Thạnh",
      "Quận Đồ Sơn",
      "Quận Dương Kinh",
      "Quận Hải An",
      "Quận Hồng Bàng",
      "Quận Kiến An",
      "Quận Lê Chân",
      "Quận Ngô Quyền",
      "Huyện An Dương",
      "Huyện An Lão",
      "Huyện Bạch Long Vĩ",
      "Huyện Cát Hải",
      "Huyện Kiến Thụy",
      "Huyện Thủy Nguyên",
      "Huyện Tiên Lãng",
      "Huyện Vĩnh Bảo",
      "Thành phố Long Xuyên (tỉnh lỵ)",
      "Thành phố Châu Đốc",
      "Thị xã Tân Châu",
      "Huyện An Phú",
      "Huyện Châu Phú",
      "Huyện Châu Thành",
      "Huyện Chợ Mới",
      "Huyện Phú Tân",
      "Huyện Thoại Sơn",
      "Huyện Tịnh Biên",
      "Huyện Tri Tôn",
      "Thành phố Bà Rịa (tỉnh lỵ)",
      "Thành phố Vũng Tàu",
      "Thị xã Phú Mỹ",
      "Huyện Châu Đức",
      "Huyện Côn Đảo",
      "Huyện Đất Đỏ",
      "Huyện Long Điền",
      "Huyện Xuyên Mộc",
      "Thành phố Bắc Giang (tỉnh lỵ)",
      "Huyện Hiệp Hòa",
      "Huyện Lạng Giang",
      "Huyện Lục Nam",
      "Huyện Lục Ngạn",
      "Huyện Sơn Động",
      "Huyện Tân Yên",
      "Huyện Việt Yên",
      "Huyện Yên Dũng",
      "Huyện Yên Thế",
      "Thành phố Bắc Kạn (tỉnh lỵ)",
      "Huyện Ba Bể",
      "Huyện Bạch Thông",
      "Huyện Chợ Đồn",
      "Huyện Chợ Mới",
      "Huyện Na Rì",
      "Huyện Ngân Sơn",
      "Huyện Pác Nặm",
      "Thành phố Bạc Liêu (tỉnh lỵ)",
      "Thị xã Giá Rai",
      "Huyện Đông Hải",
      "Huyện Hòa Bình",
      "Huyện Hồng Dân",
      "Huyện Phước Long",
      "Huyện Vĩnh Lợi",
      "Thành phố Bắc Ninh (tỉnh lỵ)",
      "Thị xã Từ Sơn",
      "Huyện Gia Bình",
      "Huyện Lương Tài",
      "Huyện Quế Võ",
      "Huyện Thuận Thành",
      "Huyện Tiên Du",
      "Huyện Yên Phong",
      "Thành phố Bến Tre (tỉnh lỵ)",
      "Huyện Ba Tri",
      "Huyện Bình Đại",
      "Huyện Châu Thành",
      "Huyện Chợ Lách",
      "Huyện Giồng Trôm",
      "Huyện Mỏ Cày Bắc",
      "Huyện Mỏ Cày Nam",
      "Huyện Thạnh Phú",
      "Thành phố Quy Nhơn (tỉnh lỵ)",
      "Thị xã An Nhơn",
      "Thị xã Hoài Nhơn",
      "Huyện An Lão",
      "Huyện Hoài Ân",
      "Huyện Phù Cát",
      "Huyện Phù Mỹ",
      "Huyện Tây Sơn",
      "Huyện Tuy Phước",
      "Huyện Vân Canh",
      "Huyện Vĩnh Thạnh",
      "Thành phố Thủ Dầu Một (tỉnh lỵ)",
      "Thành phố Dĩ An",
      "Thành phố Thuận An",
      "Thị xã Bến Cát",
      "Thị xã Tân Uyên",
      "Huyện Bắc Tân Uyên",
      "Huyện Bàu Bàng",
      "Huyện Dầu Tiếng",
      "Huyện Phú Giáo",
      "Thành phố Đồng Xoài (tỉnh lỵ)",
      "Thị xã Bình Long",
      "Thị xã Phước Long",
      "Huyện Bù Đăng",
      "Huyện Bù Đốp",
      "Huyện Bù Gia Mập",
      "Huyện Chơn Thành",
      "Huyện Đồng Phú",
      "Huyện Hớn Quản",
      "Huyện Lộc Ninh",
      "Huyện Phú Riềng",
      "Thành phố Phan Thiết (tỉnh lỵ)",
      "Thị xã La Gi",
      "Huyện Bắc Bình",
      "Huyện Đức Linh",
      "Huyện Hàm Tân",
      "Huyện Hàm Thuận Bắc",
      "Huyện Hàm Thuận Nam",
      "Huyện Phú Quý",
      "Huyện Tánh Linh",
      "Huyện Tuy Phong",
      "Thành phố Cà Mau (tỉnh lỵ)",
      "Huyện Cái Nước",
      "Huyện Đầm Dơi",
      "Huyện Năm Căn",
      "Huyện Ngọc Hiển",
      "Huyện Phú Tân",
      "Huyện Thới Bình",
      "Huyện Trần Văn Thời",
      "Huyện U Minh",
      "Thành phố Cao Bằng (tỉnh lỵ)",
      "Huyện Bảo Lạc",
      "Huyện Bảo Lâm",
      "Huyện Hạ Lang",
      "Huyện Hà Quảng",
      "Huyện Hòa An",
      "Huyện Nguyên Bình",
      "Huyện Quảng Hòa",
      "Huyện Thạch An",
      "Huyện Trùng Khánh",
      "Thành phố Buôn Ma Thuột (tỉnh lỵ)",
      "Thị xã Buôn Hồ",
      "Huyện Buôn Đôn",
      "Huyện Cư Kuin",
      "Huyện Cư M'gar",
      "Huyện Ea H'leo",
      "Huyện Ea Kar",
      "Huyện Ea Súp",
      "Huyện Krông Ana",
      "Huyện Krông Bông",
      "Huyện Krông Búk",
      "Huyện Krông Năng",
      "Huyện Krông Pắk",
      "Huyện Lắk",
      "Huyện M'Drắk",
      "Thành phố Gia Nghĩa (tỉnh lỵ)",
      "Huyện Cư Jút",
      "Huyện Đắk Glong",
      "Huyện Đắk Mil",
      "Huyện Đắk R'lấp",
      "Huyện Đắk Song",
      "Huyện Krông Nô",
      "Huyện Tuy Đức",
      "Thành phố Điện Biên Phủ (tỉnh lỵ)",
      "Thị xã Mường Lay",
      "Huyện Điện Biên",
      "Huyện Điện Biên Đông",
      "Huyện Mường Ảng",
      "Huyện Mường Chà",
      "Huyện Mường Nhé",
      "Huyện Nậm Pồ",
      "Huyện Tủa Chùa",
      "Huyện Tuần Giáo",
      "Thành phố Biên Hòa (tỉnh lỵ)",
      "Thành phố Long Khánh",
      "Huyện Cẩm Mỹ",
      "Huyện Định Quán",
      "Huyện Long Thành",
      "Huyện Nhơn Trạch",
      "Huyện Tân Phú",
      "Huyện Thống Nhất",
      "Huyện Trảng Bom",
      "Huyện Vĩnh Cửu",
      "Huyện Xuân Lộc",
      "Thành phố Cao Lãnh (tỉnh lỵ)",
      "Thành phố Hồng Ngự",
      "Thành phố Sa Đéc",
      "Huyện Cao Lãnh",
      "Huyện Châu Thành",
      "Huyện Hồng Ngự",
      "Huyện Lai Vung",
      "Huyện Lấp Vò",
      "Huyện Tam Nông",
      "Huyện Tân Hồng",
      "Huyện Thanh Bình",
      "Huyện Tháp Mười",
      "Thành phố Pleiku (tỉnh lỵ)",
      "Thị xã An Khê",
      "Thị xã Ayun Pa",
      "Huyện Chư Păh",
      "Huyện Chư Prông",
      "Huyện Chư Pưh",
      "Huyện Chư Sê",
      "Huyện Đak Đoa",
      "Huyện Đak Pơ",
      "Huyện Đức Cơ",
      "Huyện Ia Grai",
      "Huyện Ia Pa",
      "Huyện Kbang",
      "Huyện Kông Chro",
      "Huyện Krông Pa",
      "Huyện Mang Yang",
      "Huyện Phú Thiện",
      "Thành phố Hà Giang (tỉnh lỵ)",
      "Huyện Bắc Mê",
      "Huyện Bắc Quang",
      "Huyện Đồng Văn",
      "Huyện Hoàng Su Phì",
      "Huyện Mèo Vạc",
      "Huyện Quản Bạ",
      "Huyện Quang Bình",
      "Huyện Vị Xuyên",
      "Huyện Xín Mần",
      "Huyện Yên Minh",
      "Thành phố Phủ Lý (tỉnh lỵ)",
      "Thị xã Duy Tiên",
      "Huyện Bình Lục",
      "Huyện Kim Bảng",
      "Huyện Lý Nhân",
      "Huyện Thanh Liêm",
      "Thành phố Hà Tĩnh (tỉnh lỵ)",
      "Thị xã Hồng Lĩnh",
      "Thị xã Kỳ Anh",
      "Huyện Cẩm Xuyên",
      "Huyện Can Lộc",
      "Huyện Đức Thọ",
      "Huyện Hương Khê",
      "Huyện Hương Sơn",
      "Huyện Kỳ Anh",
      "Huyện Lộc Hà",
      "Huyện Nghi Xuân",
      "Huyện Thạch Hà",
      "Huyện Vũ Quang",
      "Thành phố Hải Dương (tỉnh lỵ)",
      "Thành phố Chí Linh",
      "Thị xã Kinh Môn",
      "Huyện Bình Giang",
      "Huyện Cẩm Giàng",
      "Huyện Gia Lộc",
      "Huyện Kim Thành",
      "Huyện Nam Sách",
      "Huyện Ninh Giang",
      "Huyện Thanh Hà",
      "Huyện Thanh Miện",
      "Huyện Tứ Kỳ",
      "Thành phố Vị Thanh (tỉnh lỵ)",
      "Thành phố Ngã Bảy",
      "Thị xã Long Mỹ",
      "Huyện Châu Thành",
      "Huyện Châu Thành A",
      "Huyện Long Mỹ",
      "Huyện Phụng Hiệp",
      "Huyện Vị Thủy",
      "Thành phố Hòa Bình (tỉnh lỵ)",
      "Huyện Cao Phong",
      "Huyện Đà Bắc",
      "Huyện Kim Bôi",
      "Huyện Lạc Sơn",
      "Huyện Lạc Thủy",
      "Huyện Lương Sơn",
      "Huyện Mai Châu",
      "Huyện Tân Lạc",
      "Huyện Yên Thủy",
      "Thành phố Hưng Yên (tỉnh lỵ)",
      "Thị xã Mỹ Hào",
      "Huyện Ân Thi",
      "Huyện Khoái Châu",
      "Huyện Kim Động",
      "Huyện Phù Cừ",
      "Huyện Tiên Lữ",
      "Huyện Văn Giang",
      "Huyện Văn Lâm",
      "Huyện Yên Mỹ",
      "Thành phố Nha Trang (tỉnh lỵ)",
      "Thành phố Cam Ranh",
      "Thị xã Ninh Hòa",
      "Huyện Cam Lâm",
      "Huyện Diên Khánh",
      "Huyện Khánh Sơn",
      "Huyện Khánh Vĩnh",
      "Huyện Trường Sa",
      "Huyện Vạn Ninh",
      "Thành phố Rạch Giá (tỉnh lỵ)",
      "Thành phố Hà Tiên",
      "Thành phố Phú Quốc",
      "Huyện An Biên",
      "Huyện An Minh",
      "Huyện Châu Thành",
      "Huyện Giang Thành",
      "Huyện Giồng Riềng",
      "Huyện Gò Quao",
      "Huyện Hòn Đất",
      "Huyện Kiên Hải",
      "Huyện Kiên Lương",
      "Huyện Tân Hiệp",
      "Huyện U Minh Thượng",
      "Huyện Vĩnh Thuận",
      "Thành phố Kon Tum (tỉnh lỵ)",
      "Huyện Đăk Glei",
      "Huyện Đăk Hà",
      "Huyện Đăk Tô",
      "Huyện Ia H'Drai",
      "Huyện Kon Plông",
      "Huyện Kon Rẫy",
      "Huyện Ngọc Hồi",
      "Huyện Sa Thầy",
      "Huyện Tu Mơ Rông",
      "Thành phố Lai Châu (tỉnh lỵ)",
      "Huyện Mường Tè",
      "Huyện Nậm Nhùn",
      "Huyện Phong Thổ",
      "Huyện Sìn Hồ",
      "Huyện Tam Đường",
      "Huyện Tân Uyên",
      "Huyện Than Uyên",
      "Thành phố Đà Lạt (tỉnh lỵ)",
      "Thành phố Bảo Lộc",
      "Huyện Bảo Lâm",
      "Huyện Cát Tiên",
      "Huyện Đạ Huoai",
      "Huyện Đạ Tẻh",
      "Huyện Đam Rông",
      "Huyện Di Linh",
      "Huyện Đơn Dương",
      "Huyện Đức Trọng",
      "Huyện Lạc Dương",
      "Huyện Lâm Hà",
      "Thành phố Lạng Sơn (tỉnh lỵ)",
      "Huyện Bắc Sơn",
      "Huyện Bình Gia",
      "Huyện Cao Lộc",
      "Huyện Chi Lăng",
      "Huyện Đình Lập",
      "Huyện Hữu Lũng",
      "Huyện Lộc Bình",
      "Huyện Tràng Định",
      "Huyện Văn Lãng",
      "Huyện Văn Quan",
      "Thành phố Lào Cai (tỉnh lỵ)",
      "Thị xã Sa Pa",
      "Huyện Bắc Hà",
      "Huyện Bảo Thắng",
      "Huyện Bảo Yên",
      "Huyện Bát Xát",
      "Huyện Mường Khương",
      "Huyện Si Ma Cai",
      "Huyện Văn Bàn",
      "Thành phố Tân An (tỉnh lỵ)",
      "Thị xã Kiến Tường",
      "Huyện Bến Lức",
      "Huyện Cần Đước",
      "Huyện Cần Giuộc",
      "Huyện Châu Thành",
      "Huyện Đức Hòa",
      "Huyện Đức Huệ",
      "Huyện Mộc Hóa",
      "Huyện Tân Hưng",
      "Huyện Tân Thạnh",
      "Huyện Tân Trụ",
      "Huyện Thạnh Hóa",
      "Huyện Thủ Thừa",
      "Huyện Vĩnh Hưng",
      "Thành phố Nam Định (tỉnh lỵ)",
      "Huyện Giao Thủy",
      "Huyện Hải Hậu",
      "Huyện Mỹ Lộc",
      "Huyện Nam Trực",
      "Huyện Nghĩa Hưng",
      "Huyện Trực Ninh",
      "Huyện Vụ Bản",
      "Huyện Xuân Trường",
      "Huyện Ý Yên",
      "Thành phố Vinh (tỉnh lỵ)",
      "Thị xã Cửa Lò",
      "Thị xã Hoàng Mai",
      "Thị xã Thái Hòa",
      "Huyện Anh Sơn",
      "Huyện Con Cuông",
      "Huyện Diễn Châu",
      "Huyện Đô Lương",
      "Huyện Hưng Nguyên",
      "Huyện Kỳ Sơn",
      "Huyện Nam Đàn",
      "Huyện Nghi Lộc",
      "Huyện Nghĩa Đàn",
      "Huyện Quế Phong",
      "Huyện Quỳ Châu",
      "Huyện Quỳ Hợp",
      "Huyện Quỳnh Lưu",
      "Huyện Tân Kỳ",
      "Huyện Thanh Chương",
      "Huyện Tương Dương",
      "Huyện Yên Thành",
      "Thành phố Ninh Bình (tỉnh lỵ)",
      "Thành phố Tam Điệp",
      "Huyện Gia Viễn",
      "Huyện Hoa Lư",
      "Huyện Kim Sơn",
      "Huyện Nho Quan",
      "Huyện Yên Khánh",
      "Huyện Yên Mô",
      "Thành phố Phan Rang - Tháp Chàm (tỉnh lỵ)",
      "Huyện Bác Ái",
      "Huyện Ninh Hải",
      "Huyện Ninh Phước",
      "Huyện Ninh Sơn",
      "Huyện Thuận Bắc",
      "Huyện Thuận Nam",
      "Thành phố Việt Trì (tỉnh lỵ)",
      "Thị xã Phú Thọ",
      "Huyện Cẩm Khê",
      "Huyện Đoan Hùng",
      "Huyện Hạ Hòa",
      "Huyện Lâm Thao",
      "Huyện Phù Ninh",
      "Huyện Tam Nông",
      "Huyện Tân Sơn",
      "Huyện Thanh Ba",
      "Huyện Thanh Sơn",
      "Huyện Thanh Thủy",
      "Huyện Yên Lập",
      "Thành phố Tuy Hòa (tỉnh lỵ)",
      "Thị xã Đông Hòa",
      "Thị xã Sông Cầu",
      "Huyện Đồng Xuân",
      "Huyện Phú Hòa",
      "Huyện Sơn Hòa",
      "Huyện Sông Hinh",
      "Huyện Tây Hòa",
      "Huyện Tuy An",
      "Thành phố Đồng Hới (tỉnh lỵ)",
      "Thị xã Ba Đồn",
      "Huyện Bố Trạch",
      "Huyện Lệ Thủy",
      "Huyện Minh Hóa",
      "Huyện Quảng Ninh",
      "Huyện Quảng Trạch",
      "Huyện Tuyên Hóa",
      "Thành phố Tam Kỳ (tỉnh lỵ)",
      "Thành phố Hội An",
      "Thị xã Điện Bàn",
      "Huyện Bắc Trà My",
      "Huyện Đại Lộc",
      "Huyện Đông Giang",
      "Huyện Duy Xuyên",
      "Huyện Hiệp Đức",
      "Huyện Nam Giang",
      "Huyện Nam Trà My",
      "Huyện Nông Sơn",
      "Huyện Núi Thành",
      "Huyện Phú Ninh",
      "Huyện Phước Sơn",
      "Huyện Quế Sơn",
      "Huyện Tây Giang",
      "Huyện Thăng Bình",
      "Huyện Tiên Phước",
      "Thành phố Quảng Ngãi (tỉnh lỵ)",
      "Thị xã Đức Phổ",
      "Huyện Ba Tơ",
      "Huyện Bình Sơn",
      "Huyện Lý Sơn",
      "Huyện Minh Long",
      "Huyện Mộ Đức",
      "Huyện Nghĩa Hành",
      "Huyện Sơn Hà",
      "Huyện Sơn Tây",
      "Huyện Sơn Tịnh",
      "Huyện Trà Bồng",
      "Huyện Tư Nghĩa",
      "Thành phố Hạ Long (tỉnh lỵ)",
      "Thành phố Cẩm Phả",
      "Thành phố Móng Cái",
      "Thành phố Uông Bí",
      "Thị xã Đông Triều",
      "Thị xã Quảng Yên",
      "Huyện Ba Chẽ",
      "Huyện Bình Liêu",
      "Huyện Cô Tô",
      "Huyện Đầm Hà",
      "Huyện Hải Hà",
      "Huyện Tiên Yên",
      "Huyện Vân Đồn",
      "Thành phố Đông Hà (tỉnh lỵ)",
      "Thị xã Quảng Trị",
      "Huyện Cam Lộ",
      "Huyện Cồn Cỏ",
      "Huyện Đakrông",
      "Huyện Gio Linh",
      "Huyện Hải Lăng",
      "Huyện Hướng Hóa",
      "Huyện Triệu Phong",
      "Huyện Vĩnh Linh",
      "Thành phố Sóc Trăng (tỉnh lỵ)",
      "Thị xã Ngã Năm",
      "Thị xã Vĩnh Châu",
      "Huyện Châu Thành",
      "Huyện Cù Lao Dung",
      "Huyện Kế Sách",
      "Huyện Long Phú",
      "Huyện Mỹ Tú",
      "Huyện Mỹ Xuyên",
      "Huyện Thạnh Trị",
      "Huyện Trần Đề",
      "Thành phố Sơn La (tỉnh lỵ)",
      "Huyện Bắc Yên",
      "Huyện Mai Sơn",
      "Huyện Mộc Châu",
      "Huyện Mường La",
      "Huyện Phù Yên",
      "Huyện Quỳnh Nhai",
      "Huyện Sông Mã",
      "Huyện Sốp Cộp",
      "Huyện Thuận Châu",
      "Huyện Vân Hồ",
      "Huyện Yên Châu",
      "Thành phố Tây Ninh (tỉnh lỵ)",
      "Thị xã Hòa Thành",
      "Thị xã Trảng Bàng",
      "Huyện Bến Cầu",
      "Huyện Châu Thành",
      "Huyện Dương Minh Châu",
      "Huyện Gò Dầu",
      "Huyện Tân Biên",
      "Huyện Tân Châu",
      "Thành phố Thái Bình (tỉnh lỵ)",
      "Huyện Đông Hưng",
      "Huyện Hưng Hà",
      "Huyện Kiến Xương",
      "Huyện Quỳnh Phụ",
      "Huyện Thái Thụy",
      "Huyện Tiền Hải",
      "Huyện Vũ Thư",
      "Thành phố Thái Nguyên (tỉnh lỵ)",
      "Thành phố Sông Công",
      "Thị xã Phổ Yên",
      "Huyện Đại Từ",
      "Huyện Định Hóa",
      "Huyện Đồng Hỷ",
      "Huyện Phú Bình",
      "Huyện Phú Lương",
      "Huyện Võ Nhai",
      "Thành phố Thanh Hóa (tỉnh lỵ)",
      "Thành phố Sầm Sơn",
      "Thị xã Bỉm Sơn",
      "Thị xã Nghi Sơn",
      "Huyện Bá Thước",
      "Huyện Cẩm Thủy",
      "Huyện Đông Sơn",
      "Huyện Hà Trung",
      "Huyện Hậu Lộc",
      "Huyện Hoằng Hóa",
      "Huyện Lang Chánh",
      "Huyện Mường Lát",
      "Huyện Nga Sơn",
      "Huyện Ngọc Lặc",
      "Huyện Như Thanh",
      "Huyện Như Xuân",
      "Huyện Nông Cống",
      "Huyện Quan Hóa",
      "Huyện Quan Sơn",
      "Huyện Quảng Xương",
      "Huyện Thạch Thành",
      "Huyện Thiệu Hóa",
      "Huyện Thọ Xuân",
      "Huyện Thường Xuân",
      "Huyện Triệu Sơn",
      "Huyện Vĩnh Lộc",
      "Huyện Yên Định",
      "Thành phố Huế (tỉnh lỵ)",
      "Thị xã Hương Thủy",
      "Thị xã Hương Trà",
      "Huyện A Lưới",
      "Huyện Nam Đông",
      "Huyện Phong Điền",
      "Huyện Phú Lộc",
      "Huyện Phú Vang",
      "Huyện Quảng Điền",
      "Thành phố Mỹ Tho (tỉnh lỵ)",
      "Thị xã Cai Lậy",
      "Thị xã Gò Công",
      "Huyện Cái Bè",
      "Huyện Cai Lậy",
      "Huyện Châu Thành",
      "Huyện Chợ Gạo",
      "Huyện Gò Công Đông",
      "Huyện Gò Công Tây",
      "Huyện Tân Phú Đông",
      "Huyện Tân Phước",
      "Thành phố Trà Vinh (tỉnh lỵ)",
      "Thị xã Duyên Hải",
      "Huyện Càng Long",
      "Huyện Cầu Kè",
      "Huyện Cầu Ngang",
      "Huyện Châu Thành",
      "Huyện Duyên Hải",
      "Huyện Tiểu Cần",
      "Huyện Trà Cú",
      "Thành phố Tuyên Quang (tỉnh lỵ)",
      "Huyện Chiêm Hóa",
      "Huyện Hàm Yên",
      "Huyện Lâm Bình",
      "Huyện Na Hang",
      "Huyện Sơn Dương",
      "Huyện Yên Sơn",
      "Thành phố Vĩnh Long (tỉnh lỵ)",
      "Thị xã Bình Minh",
      "Huyện Bình Tân",
      "Huyện Long Hồ",
      "Huyện Mang Thít",
      "Huyện Tam Bình",
      "Huyện Trà Ôn",
      "Huyện Vũng Liêm",
      "Thành phố Vĩnh Yên (tỉnh lỵ)",
      "Thành phố Phúc Yên",
      "Huyện Bình Xuyên",
      "Huyện Lập Thạch",
      "Huyện Sông Lô",
      "Huyện Tam Đảo",
      "Huyện Tam Dương",
      "Huyện Vĩnh Tường",
      "Huyện Yên Lạc",
      "Thành phố Yên Bái (tỉnh lỵ)",
      "Thị xã Nghĩa Lộ",
      "Huyện Lục Yên",
      "Huyện Mù Cang Chải",
      "Huyện Trạm Tấu",
      "Huyện Trấn Yên",
      "Huyện Văn Chấn",
      "Huyện Văn Yên",
      "Huyện Yên Bình",
    ],
    cities: [
      "Hà Nội",
      "Hồ Chí Minh",
      "Đà Nẵng",
      "Cần Thơ",
      "Hải Phòng",
      "An Giang",
      "Bà Rịa-Vũng Tàu",
      "Bắc Giang",
      "Bắc Kạn",
      "Bạc Liêu",
      "Bắc Ninh",
      "Bến Tre",
      "Bình Định",
      "Bình Dương",
      "Bình Phước",
      "Bình Thuận",
      "Cà Mau",
      "Cao Bằng",
      "Đắk Lắk",
      "Đắk Nông",
      "Điện Biên",
      "Đồng Nai",
      "Đồng Tháp",
      "Gia Lai",
      "Hà Giang",
      "Hà Nam",
      "Hà Tĩnh",
      "Hải Dương",
      "Hậu Giang",
      "Hòa Bình",
      "Hưng Yên",
      "Khánh Hòa",
      "Kiên Giang",
      "Kon Tum",
      "Lai Châu",
      "Lâm Đồng",
      "Lạng Sơn",
      "Lào Cai",
      "Long An",
      "Nam Định",
      "Nghệ An",
      "Ninh Bình",
      "Ninh Thuận",
      "Phú Thọ",
      "Phú Yên",
      "Quảng Bình",
      "Quảng Nam",
      "Quảng Ngãi",
      "Quảng Ninh",
      "Quảng Trị",
      "Sóc Trăng",
      "Sơn La",
      "Tây Ninh",
      "Thái Bình",
      "Thái Nguyên",
      "Thanh Hóa",
      "Thừa Thiên Huế",
      "Tiền Giang",
      "Trà Vinh",
      "Tuyên Quang",
      "Vĩnh Long",
      "Vĩnh Phúc",
      "Yên Bái",
    ],
  },

  isError: false,
  isSuccess: false,
  isLoading: false,
  message: "",
};

export const addressesSlice = createSlice({
  name: "address",
  initialState,
  reducers: {
    reset: (state) => initialState,
  },
});

export const { reset } = addressesSlice.actions;

export const selectSubDistrict = (state) =>
  state.address.addresses.sub_district;
export const selectDistrict = (state) => state.address.addresses.districts;
export const selectCity = (state) => state.address.addresses.cities;

export default addressesSlice.reducer;
